name: Bruno API Tests

on:
  pull_request:
    branches: ["main"]
    paths:
      - "bruno/**"
      - ".github/workflows/bruno.yml"
      - ".github/workflows/bruno-tests.yml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  bruno:
    uses: ./.github/workflows/bruno.yml
    secrets: inherit
